refactor: use sdk.Dec for quantities
crescent-network/crescent pull request #168
Opened 2023-07-19 08:07 UTC by kingcre

## Description

Use `sdk.Dec` instead of `sdk.Int`(also `sdk.DecCoin` instead of `sdk.Coin`) in x/exchange. This will reduce errors caused by decimal truncation.

## Tasks

- [x] Refactor codebase
- [ ] Write tests for decimal quantities

2023-07-31 01:03 UTC, crypin commented
Please let me know when it ready for review

2023-07-31 07:56 UTC, kingcre commented
@crypin It's now ready

2023-08-02 08:23 UTC, crypin requested changes

2023-08-02 08:23 UTC, crypin commented on x/amm/keeper/source.go
> +			panic(amtInDiff)
I think this part is likely to happen, I will share the detailed scenario again as soon as it is sorted out

2023-08-02 12:27 UTC, kingcre commented on x/amm/keeper/invariants.go
>  	ir.RegisterRoute(types.ModuleName, "can-collect", CanCollectInvariant(k))
Actually we were already using cached context inside `CollectibleCoins`:
https://github.com/crescent-network/crescent/blob/e5a01f970a4c80ad9008a8413e6534e7b04be86a/x/amm/keeper/position.go#L187-L195

2023-08-03 01:47 UTC, crypin commented on x/amm/keeper/invariants.go
>  	ir.RegisterRoute(types.ModuleName, "can-collect", CanCollectInvariant(k))
Oh, I said it wrong, the state transition occurs without cached ctx in the `Collect` of this part, 

https://github.com/crescent-network/crescent/blob/e5a01f970a4c80ad9008a8413e6534e7b04be86a/x/amm/keeper/invariants.go#L118

so i think the determinism can be broken depending on whether or not there is Invariant checking config for each node

2023-08-03 03:35 UTC, kingcre commented on x/amm/keeper/invariants.go
>  	ir.RegisterRoute(types.ModuleName, "can-collect", CanCollectInvariant(k))
Oh, that's right. Fixed it.

2023-08-07 05:28 UTC, kingcre commented
Merging this PR and the remaining issues will be handled in separate issues.

2023-08-07 05:28 UTC, merged